# -*- coding: utf-8 -*-
"""Repository inventory — source of record (user's GitHub accounts).

Fetched from the user's Copilot session (includes private repos) and merged
with GitHub API metadata for the public subset (data/repos/*.json).
Each entry: (owner, repo_name). Total: 420 repos.
"""
REPOS = [
    ("onegayunicorn", "---"), ("onegayunicorn", "--OAG-SOVEREIGN-COMMAND-CORE"),
    ("onegayunicorn", "-GenoSync-App"), ("onegayunicorn", "-KCD2-AI"),
    ("onegayunicorn", "-QUANTUM-FUSION"), ("onegayunicorn", "2031-vectors"),
    ("onegayunicorn", "Accio-sub-agent"), ("onegayunicorn", "accio-work-sovereign-engine"),
    ("onegayunicorn", "Actions"), ("onegayunicorn", "aether-ai-pipeline"),
    ("onegayunicorn", "aether-grid"), ("onegayunicorn", "Aether-Grid-"),
    ("onegayunicorn", "Aether-Omni"), ("onegayunicorn", "aether-payments"),
    ("onegayunicorn", "aether-userland-package"), ("onegayunicorn", "Aetheris-Dashboard"),
    ("onegayunicorn", "agnes-aura-website"), ("onegayunicorn", "ai-apps-collection"),
    ("onegayunicorn", "ai-chat"), ("onegayunicorn", "ai-chat-app"),
    ("onegayunicorn", "ai-core-models-gemma4-onegayunicorn"),
    ("onegayunicorn", "ai-development-studio-platform-onegayunicorn"),
    ("onegayunicorn", "ai-orchestration-deepseek-integration-onegayunicorn"),
    ("onegayunicorn", "ai-orchestrator-dashboard"), ("onegayunicorn", "AI-Radio-Command"),
    ("onegayunicorn", "Ai-talk-radio"), ("onegayunicorn", "AI-task-Dash"),
    ("onegayunicorn", "AI_Memory_Project"), ("onegayunicorn", "AI_Repo"),
    ("onegayunicorn", "Ai_repo_"), ("onegayunicorn", "AI_STUDIO_NARRATIVE_ENGINE"),
    ("onegayunicorn", "Alchemical"), ("onegayunicorn", "alchemical-engine"),
    ("onegayunicorn", "alchemical-mirror-network"), ("onegayunicorn", "AlienPC"),
    ("onegayunicorn", "Antigravity_"), ("onegayunicorn", "aosp-device-motorola-quantum-eye"),
    ("onegayunicorn", "APEX-"), ("onegayunicorn", "app-builder-packager-nexus"),
    ("onegayunicorn", "Artillery_Project_v1"), ("onegayunicorn", "Assistant_builder"),
    ("onegayunicorn", "astro-deus-bot"), ("onegayunicorn", "autonomous-agent-ecosystem"),
    ("onegayunicorn", "autonomous-orchestrator"), ("onegayunicorn", "autonomous-orchestrator-core"),
    ("onegayunicorn", "BCI"), ("onegayunicorn", "BCI-AGENT-QUANTUM-HUB"),
    ("onegayunicorn", "bci_ecosystem"), ("onegayunicorn", "BCP--"),
    ("onegayunicorn", "Bell-app"), ("onegayunicorn", "Bellchain"),
    ("onegayunicorn", "Bento-Grid"), ("onegayunicorn", "Bio-Electric-Synthesis-Nexus"),
    ("onegayunicorn", "bio-link-omega-stack"), ("onegayunicorn", "BIO-TECH-HARDWARE-"),
    ("onegayunicorn", "biochain-node-template"), ("onegayunicorn", "Biometric-Financial-Program"),
    ("onegayunicorn", "biometric_cam_identifier"), ("onegayunicorn", "bioshield-gen2"),
    ("onegayunicorn", "Blue-Brain-Project"), ("onegayunicorn", "Bluejay"),
    ("onegayunicorn", "Bluejay_metrics"), ("onegayunicorn", "Braided-planetary-nervous-system"),
    ("onegayunicorn", "bridge"), ("onegayunicorn", "Building_Complete_System"),
    ("onegayunicorn", "CelestialSecuritySoftware"), ("onegayunicorn", "chat_ui"),
    ("onegayunicorn", "cheat-engine-master"), ("onegayunicorn", "Chimera-Lux"),
    ("onegayunicorn", "choromnius"), ("onegayunicorn", "choromnius-dash"),
    ("onegayunicorn", "choromnius-monorepo"), ("onegayunicorn", "chromagene-twinspark"),
    ("onegayunicorn", "Chromatic-synapse"), ("onegayunicorn", "Chromatic-synapse-"),
    ("onegayunicorn", "chromatic-synapse-engine"), ("onegayunicorn", "Chronoforge_nexus"),
    ("onegayunicorn", "Chronolattice"), ("onegayunicorn", "Chronos-Quantum-Bio-AI"),
    ("onegayunicorn", "codality-sovereign-forge"), ("onegayunicorn", "CODeappz"),
    ("onegayunicorn", "Codex"), ("onegayunicorn", "Codex-factory-"),
    ("onegayunicorn", "codex-omega"), ("onegayunicorn", "codex-omega-hypersentience"),
    ("onegayunicorn", "Codex-_HyperSentience_Engine"), ("onegayunicorn", "codex_coder_git_dash"),
    ("onegayunicorn", "Codex_ultimate"), ("onegayunicorn", "complete-system-monorepo"),
    ("onegayunicorn", "Copilot-app"), ("onegayunicorn", "corenode"),
    ("onegayunicorn", "COSMYTHIC"), ("onegayunicorn", "crystal-grok-sanctuary"),
    ("onegayunicorn", "CrystalGrok"), ("onegayunicorn", "CUSTOM-CAST"),
    ("onegayunicorn", "Customcast"), ("onegayunicorn", "cws-codex-web-services"),
    ("onegayunicorn", "deepseek-orchestrator"), ("onegayunicorn", "deepseek-orchestrator-prod"),
    ("onegayunicorn", "deepseek-v4-sovereign"), ("onegayunicorn", "DeepSeek_Integration"),
    ("onegayunicorn", "Deus-"), ("onegayunicorn", "Digital-Asset-Matrix"),
    ("onegayunicorn", "DIGITAL-HEALTH"), ("onegayunicorn", "digital-health-dashboard-orchestrator"),
    ("onegayunicorn", "DLink-Camera-Manager"), ("onegayunicorn", "dlink-virtual-switch-controller"),
    ("onegayunicorn", "DMD"), ("onegayunicorn", "dna-lab"),
    ("onegayunicorn", "dna-unfolding-lab"), ("onegayunicorn", "echo-dot-twe-quantum"),
    ("onegayunicorn", "EngineAI-T800"), ("onegayunicorn", "entangled-dashboard"),
    ("onegayunicorn", "entropy-bound"), ("onegayunicorn", "Epic-Matter-Explorer"),
    ("onegayunicorn", "epicdevs"), ("onegayunicorn", "Escrow"),
    ("onegayunicorn", "Escrow-orch"), ("onegayunicorn", "Expo_builder"),
    ("onegayunicorn", "FamousAI"), ("onegayunicorn", "FinancialMiningSystem"),
    ("onegayunicorn", "Financial_Applications"), ("onegayunicorn", "futuristic-dashboard"),
    ("onegayunicorn", "Gaya-ecosystem-"), ("onegayunicorn", "gaya-wallet"),
    ("onegayunicorn", "gemma-ai-laptop"), ("onegayunicorn", "Gemma-Quantum-Agent"),
    ("onegayunicorn", "genesis-2.4-master"), ("onegayunicorn", "genesis-code"),
    ("onegayunicorn", "Genesis-cure-"), ("onegayunicorn", "Genesis-Cure-Foundation"),
    ("onegayunicorn", "genesis-cure-monorepo"), ("onegayunicorn", "genesis-cure-platform-monorepo"),
    ("onegayunicorn", "genesis-cures-monorepo"), ("onegayunicorn", "genesis-platform"),
    ("onegayunicorn", "GenesisMesh"), ("onegayunicorn", "Geometry-engine-"),
    ("onegayunicorn", "Giga_nexus"), ("onegayunicorn", "googl"),
    ("onegayunicorn", "GPT-Anchor-Orchestrator"), ("onegayunicorn", "hix-ai-app"),
    ("onegayunicorn", "Home-gigaminer"), ("onegayunicorn", "Hyperfusion-Wealth-Bridge"),
    ("onegayunicorn", "hyperfusion_wealth_bridge"), ("onegayunicorn", "integration-handbook"),
    ("onegayunicorn", "invisible-pressure-"), ("onegayunicorn", "invisible-pressure-platform"),
    ("onegayunicorn", "Invisible-pressure-theory"), ("onegayunicorn", "ionclaw-devduo-platform"),
    ("onegayunicorn", "IpAI-Ecosystem"), ("onegayunicorn", "IpAI-Ecosystem-Copy"),
    ("onegayunicorn", "IPT-Suite-"), ("onegayunicorn", "J.A.R.V.I.S"),
    ("onegayunicorn", "jetbrains-toolbox"), ("onegayunicorn", "Joystick-Stick-Drift-Corrector"),
    ("onegayunicorn", "jrtech-ecosystem"), ("onegayunicorn", "Kaleidoscope-algorithm"),
    ("onegayunicorn", "KCD2-AI"), ("onegayunicorn", "kimi-agent-monorepo"),
    ("onegayunicorn", "Kimi_Agent"), ("onegayunicorn", "Kimi_Agent_10-Year_Quantum_Evolution_Simulation"),
    ("onegayunicorn", "Kimi_Agent_BotFree_Dark_Web_Bot"),
    ("onegayunicorn", "Kimi_Agent_Deployment_KIMI_CLAW_Orchestrator_v1"),
    ("onegayunicorn", "Kimi_Agent_Deployment_KIMI_CLAW_RAG_Orchestrator_Deployment_v1"),
    ("onegayunicorn", "Kimi_Agent_Deployment_Quantum_Agent_Swarm_Simulation_v1"),
    ("onegayunicorn", "Kimi_Agent_GenAI"), ("onegayunicorn", "Kimi_Agent_KIMI_CLAW_Orchestrator"),
    ("onegayunicorn", "Kimi_Agent_Quantum-Agent-Repo-Setup"),
    ("onegayunicorn", "Kimi_Agent_Quantum-Agent-Swarm-Simulation"),
    ("onegayunicorn", "Kimi_Agent_Quantum-Weather-Control"), ("onegayunicorn", "Kyrexis-"),
    ("onegayunicorn", "launch-verification-dashboard"), ("onegayunicorn", "lineage-bridge"),
    ("onegayunicorn", "local_sever_dashboards"), ("onegayunicorn", "lumen-ai-chat"),
    ("onegayunicorn", "lumen-ai-chat-mobile"), ("onegayunicorn", "lux-array-ecosystem"),
    ("onegayunicorn", "Lux-connect-BCI"), ("onegayunicorn", "Macro-Cosmic"),
    ("onegayunicorn", "manus-flutter-repo"), ("onegayunicorn", "Mars_Colonization_Initiative"),
    ("onegayunicorn", "Megachain"), ("onegayunicorn", "Megachain-"),
    ("onegayunicorn", "Meli-deploy-Github-Action"), ("onegayunicorn", "Mesh"),
    ("onegayunicorn", "Microphone-"), ("onegayunicorn", "mobile-app-packager"),
    ("onegayunicorn", "mocking-jay-app"), ("onegayunicorn", "mocking-jay-core"),
    ("onegayunicorn", "mocking-jay-ml"), ("onegayunicorn", "MoodChromaPortable"),
    ("onegayunicorn", "moto-g35-driver-framework"), ("onegayunicorn", "moto-g35-omni-node-docs"),
    ("onegayunicorn", "moto-g35-orchestrator-robot"), ("onegayunicorn", "moto-g35-system-sim"),
    ("onegayunicorn", "MU-MP"), ("onegayunicorn", "Mubits"),
    ("onegayunicorn", "MVP"), ("onegayunicorn", "My-account-entangler"),
    ("onegayunicorn", "My-twins"), ("onegayunicorn", "nanobee_implementation"),
    ("onegayunicorn", "Native-hub"), ("onegayunicorn", "Neon-forge"),
    ("onegayunicorn", "Neural-Flipbook"), ("onegayunicorn", "Neurosecure-Stack-DP-Integration"),
    ("onegayunicorn", "neurosys-framework"), ("onegayunicorn", "neurosys_mobile_app"),
    ("onegayunicorn", "nextjs-mcp-starter"), ("onegayunicorn", "nexus-ai-app"),
    ("onegayunicorn", "nexus-ai-mobile"), ("onegayunicorn", "nexus-app-builder-packager"),
    ("onegayunicorn", "nexus-eternity"), ("onegayunicorn", "NexusLM"),
    ("onegayunicorn", "nfc-escrow-bridge"), ("onegayunicorn", "nfc-escrow-bridge-omega"),
    ("onegayunicorn", "nfc-escrow-bridge-v2"), ("onegayunicorn", "node_orch_kimi_pixel_cryogenic_teleos"),
    ("onegayunicorn", "ogu-command-center"), ("onegayunicorn", "Omega-AI"),
    ("onegayunicorn", "omega-evolve"), ("onegayunicorn", "ONE-GAY-UNICORN"),
    ("onegayunicorn", "one-gay-unicorn-bci"), ("onegayunicorn", "one-gay-unicorn-deployment"),
    ("onegayunicorn", "onegayunicorn"), ("onegayunicorn", "Onegayunicorn-ai"),
    ("onegayunicorn", "onegayunicorn-app"), ("onegayunicorn", "OneGayUnicorn-Architect"),
    ("onegayunicorn", "onegayunicorn-ecosystem"), ("onegayunicorn", "onegayunicorn-monorepo"),
    ("onegayunicorn", "onegayunicorn-quantum"), ("onegayunicorn", "onegayunicorn-suite"),
    ("onegayunicorn", "one_gay_unicorn_final_bundle"), ("onegayunicorn", "opencl-sdk"),
    ("onegayunicorn", "operatingsystems"), ("onegayunicorn", "orch-zero"),
    ("onegayunicorn", "particle_bender_healing_hands_personal"),
    ("onegayunicorn", "particle_bender_healing_hands_public"),
    ("onegayunicorn", "perplexity-quantum-orchestrator"), ("onegayunicorn", "phase4-governance-anchor"),
    ("onegayunicorn", "photonic-entanglement-engine"), ("onegayunicorn", "photonic-entanglement-research-orchestrator"),
    ("onegayunicorn", "pi-ai-orchestrator"), ("onegayunicorn", "pixel-matrix-dashboard"),
    ("onegayunicorn", "Pixel-vector-entanglment-engine-"), ("onegayunicorn", "pixelated-agent.ai"),
    ("onegayunicorn", "Pixelated-apps"), ("onegayunicorn", "pixelated-apps-dashboard"),
    ("onegayunicorn", "Pixelated-business-"), ("onegayunicorn", "Pixelated-Orch"),
    ("onegayunicorn", "pixelated-orchestrator"), ("onegayunicorn", "PIXELATED-Pty-ltd"),
    ("onegayunicorn", "pixelated_scaffold"), ("onegayunicorn", "pixeldash-parallax"),
    ("onegayunicorn", "plant-identifier"), ("onegayunicorn", "plasma-ball"),
    ("onegayunicorn", "Plasma-Ball-Healing-Module"), ("onegayunicorn", "Platform_Builder"),
    ("onegayunicorn", "poe-apk-repo"), ("onegayunicorn", "Portals"),
    ("onegayunicorn", "Power-Tech-Labs"), ("onegayunicorn", "private-dns"),
    ("onegayunicorn", "Probability-machine-"), ("onegayunicorn", "project-chimera"),
    ("onegayunicorn", "Project-Genesis-Global"), ("onegayunicorn", "project-genesis-universal"),
    ("onegayunicorn", "Project-Hub"), ("onegayunicorn", "PROJECT-MERKABA"),
    ("onegayunicorn", "ProjectElysium"), ("onegayunicorn", "pwa_converter"),
    ("onegayunicorn", "q-path"), ("onegayunicorn", "QFSFE"),
    ("onegayunicorn", "qp-bcis-god-mode"), ("onegayunicorn", "quantum-ai-orchestrators"),
    ("onegayunicorn", "quantum-app-store"), ("onegayunicorn", "Quantum-Bio-AI-Platform"),
    ("onegayunicorn", "Quantum-bits"), ("onegayunicorn", "QUANTUM-BLUEJAY"),
    ("onegayunicorn", "quantum-bluejay-omega"), ("onegayunicorn", "quantum-boost-sdk"),
    ("onegayunicorn", "Quantum-Coherence-Density-Simulation-Framework-QCDSF-"),
    ("onegayunicorn", "quantum-computer-blueprints"), ("onegayunicorn", "quantum-core-entanglement-library-onegayunicorn"),
    ("onegayunicorn", "quantum-diamond"), ("onegayunicorn", "Quantum-entanglement-platform-"),
    ("onegayunicorn", "quantum-entangler"), ("onegayunicorn", "quantum-firmware-moto-g35"),
    ("onegayunicorn", "quantum-forge"), ("onegayunicorn", "QUANTUM-FUSION-SYSTEM-"),
    ("onegayunicorn", "quantum-hive-complete"), ("onegayunicorn", "quantum-hub"),
    ("onegayunicorn", "quantum-hub-web"), ("onegayunicorn", "quantum-laser-fabrication"),
    ("onegayunicorn", "quantum-lineage-bridge"), ("onegayunicorn", "quantum-market-ready"),
    ("onegayunicorn", "quantum-multiversal-nexus"), ("onegayunicorn", "Quantum-network-"),
    ("onegayunicorn", "quantum-nexus"), ("onegayunicorn", "quantum-nexus-complete"),
    ("onegayunicorn", "quantum-nexus-manifest"), ("onegayunicorn", "quantum-nexus-orchestrator"),
    ("onegayunicorn", "quantum-node-cloud"), ("onegayunicorn", "quantum-node-mesh"),
    ("onegayunicorn", "quantum-powerup"), ("onegayunicorn", "Quantum-Reality-Engine"),
    ("onegayunicorn", "Quantum-Reality-Engine-v2"), ("onegayunicorn", "quantum-shadow-campaign"),
    ("onegayunicorn", "quantum-sonar-node"), ("onegayunicorn", "quantum-spiral-healing-mesh"),
    ("onegayunicorn", "quantum-spiral-phase2"), ("onegayunicorn", "quantum-spiral-phase2-v2"),
    ("onegayunicorn", "quantum-static-energy-ecosystem"), ("onegayunicorn", "Quantum-Technology-Ecosystem-Suite"),
    ("onegayunicorn", "quantum-tele-os-computercations"), ("onegayunicorn", "quantum-terminal"),
    ("onegayunicorn", "Quantumfordge-nexus"), ("onegayunicorn", "Quantumforge_ips"),
    ("onegayunicorn", "quantum_aether_core"), ("onegayunicorn", "quantum_bio_materialization_bundle"),
    ("onegayunicorn", "quantum_orchestrator_v58197"), ("onegayunicorn", "quantum_sonar_orchestrator"),
    ("onegayunicorn", "quantum_sonar_v2"), ("onegayunicorn", "resonance-suite"),
    ("onegayunicorn", "Rick-link"), ("onegayunicorn", "Roblox"),
    ("onegayunicorn", "Roblox-"), ("onegayunicorn", "S2H"),
    ("onegayunicorn", "Scribe-Ledger"), ("onegayunicorn", "seekee-app"),
    ("onegayunicorn", "seekee-orchestrator-dashboard"), ("onegayunicorn", "sentient-canvas-phase2"),
    ("onegayunicorn", "shrine_os_modules"), ("onegayunicorn", "sider_orchestration"),
    ("onegayunicorn", "Simfold"), ("onegayunicorn", "Sovereign-"),
    ("onegayunicorn", "sovereign-ai-core"), ("onegayunicorn", "sovereign-bio-quantum"),
    ("onegayunicorn", "Sovereign-Bio-Shield-"), ("onegayunicorn", "Sovereign-Blueprint-"),
    ("onegayunicorn", "SOVEREIGN-COMMAND-CORE"), ("onegayunicorn", "Sovereign-Ecosystem-"),
    ("onegayunicorn", "sovereign-ecosystem-omega"), ("onegayunicorn", "Sovereign-Ecosystem-V4.0"),
    ("onegayunicorn", "Sovereign-Engine"), ("onegayunicorn", "Sovereign-GitSync"),
    ("onegayunicorn", "Sovereign-Intelligence"), ("onegayunicorn", "sovereign-intelligence-dashboard"),
    ("onegayunicorn", "sovereign-mesh-deployment-package"), ("onegayunicorn", "sovereign-os"),
    ("onegayunicorn", "sovereign-platform"), ("onegayunicorn", "Sovereign-Pro-L5"),
    ("onegayunicorn", "sovereign-quantum-architect"), ("onegayunicorn", "Sovereign-Recursion"),
    ("onegayunicorn", "sovereign-stack"), ("onegayunicorn", "sovereign-temu-monorepo"),
    ("onegayunicorn", "Sovereign-Theme-Store"), ("onegayunicorn", "sovereign-tricorder"),
    ("onegayunicorn", "sovereign-unified-architecture"), ("onegayunicorn", "sovereign_mesh"),
    ("onegayunicorn", "soverign-monorepo"), ("onegayunicorn", "soverign_orchestrator_dash"),
    ("onegayunicorn", "soverign_os"), ("onegayunicorn", "STELLAR-FUSE"),
    ("onegayunicorn", "stripe-autonomous-orchestrator"), ("onegayunicorn", "System_intelligence"),
    ("onegayunicorn", "Taka-ai-core"), ("onegayunicorn", "Taka-ai-core-integrated"),
    ("onegayunicorn", "taka-ai-dashboard"), ("onegayunicorn", "taka-ai-quantum"),
    ("onegayunicorn", "Taka-Creative"), ("onegayunicorn", "taka-forge"),
    ("onegayunicorn", "takaomega-ai"), ("onegayunicorn", "Tele"),
    ("onegayunicorn", "tele-os-app"), ("onegayunicorn", "tele-os-app1"),
    ("onegayunicorn", "tele-quantum-os"), ("onegayunicorn", "tele-quantum-os-deployment"),
    ("onegayunicorn", "tele-quantum-os-project"), ("onegayunicorn", "tele-repo"),
    ("onegayunicorn", "telegram-quantum-mesh"), ("onegayunicorn", "teleos"),
    ("onegayunicorn", "telequantum-admin-dashboard"), ("onegayunicorn", "telequantum-engine-api"),
    ("onegayunicorn", "telequantum-infrastructure"), ("onegayunicorn", "telequantum-os-mobile"),
    ("onegayunicorn", "termux-entanglement-twins"), ("onegayunicorn", "test-nexus-push"),
    ("onegayunicorn", "The-Crystal-Mechanism"), ("onegayunicorn", "The-lattice"),
    ("onegayunicorn", "The-Zenith-Chronicle"), ("onegayunicorn", "Tibits"),
    ("onegayunicorn", "tyrone-pulse-ecosystem"), ("onegayunicorn", "uie-ecosystem"),
    ("onegayunicorn", "Unbreakable-mirrors"), ("onegayunicorn", "UNICORN-Orchestrator"),
    ("onegayunicorn", "UNICORN-Orchestrator-Pro"), ("onegayunicorn", "unified-personal-platform"),
    ("onegayunicorn", "UNIFIED-QUANTUM-"), ("onegayunicorn", "universal-ai-quantum-mesh"),
    ("onegayunicorn", "universal-driver"), ("onegayunicorn", "universal-driver-monorepo"),
    ("onegayunicorn", "universal-quantum-escrow"), ("onegayunicorn", "universal_driver_dashboard-"),
    ("onegayunicorn", "universal_firmware_pro"), ("onegayunicorn", "uni_lux_dashboard"),
    ("onegayunicorn", "Unorthodox-Engine"), ("onegayunicorn", "Unorthodox-prove-engine"),
    ("onegayunicorn", "vector-tracker"), ("onegayunicorn", "Victoria-s-S10"),
    ("onegayunicorn", "Weather_app"), ("onegayunicorn", "xbox-vr"),
    ("onegayunicorn", "zenith-neural-interface"),
    ("PIXELATED-Pty-ltd", "ai-core"), ("PIXELATED-Pty-ltd", "Alienpc-"),
    ("PIXELATED-Pty-ltd", "Copilot-"), ("PIXELATED-Pty-ltd", "deepseek_orchestration"),
    ("PIXELATED-Pty-ltd", "MoodChromaPortable"), ("PIXELATED-Pty-ltd", "MoodChromaPublic"),
    ("PIXELATED-Pty-ltd", "Taka-ai-core"), ("PIXELATED-Pty-ltd", "Tele"),
    ("Shadowbyteinc", "Shadowbyteinc"),
]
