# -*- coding: utf-8 -*-
"""Spec data part B: capabilities 66-131 (of 131).

Each entry: (num, title, protocol_purpose, triggers, tasks, workflow_steps)
triggers/tasks may contain " | " separators; workflow uses " -> ".
Transcribed from the user's Cloudflare Permissions & Capabilities specification.
"""

ENTRIES_B = [
    (66, "Account Settings Write",
     "Account-level defaults, preferences, and feature toggles.",
     "AccountSettingsUpdatedTrigger",
     "UpdateAccountSettingTask",
     "Modify -> Validate -> Apply -> Sync -> Audit"),

    (67, "Billing Write",
     "Subscriptions, usage, invoices, payments, credits, and alerts for billing.",
     "UsageThresholdTrigger | InvoiceIssuedTrigger | PaymentDueTrigger",
     "UpdateBillingPlanTask | ProcessPaymentTask",
     "Calculate usage -> Generate invoice -> Charge -> Receipt -> Notify"),

    (68, "Integration Write",
     "Third-party connectors, OAuth, webhooks, and credentials for integrations.",
     "IntegrationConnectedTrigger",
     "ConfigureIntegrationTask",
     "Select -> Auth -> Configure -> Test -> Activate"),

    (69, "Notifications Write",
     "Channels, recipients, templates, triggers, and frequency for notifications.",
     "NotificationEventTrigger",
     "ConfigureNotificationTask",
     "Define channel -> Set rules -> Template -> Test -> Activate"),

    (70, "OAuth Client Write",
     "Client registration, redirect URIs, scopes, and secrets for OAuth clients.",
     "OAuthClientCreatedTrigger",
     "RegisterOAuthClientTask",
     "Register -> Configure -> Generate secret -> Whitelist -> Activate"),

    (71, "SCIM Provisioning",
     "User/group sync, provisioning, deprovisioning, and attributes via SCIM.",
     "SCIMSyncTrigger | IdentityProviderTrigger",
     "ProvisionSCIMResourceTask",
     "Pull from IdP -> Map -> Create/Update -> Deprovision -> Report"),

    (72, "SSO Connector Write",
     "SAML/OIDC, IdP configuration, claims mapping, and sign-on URL.",
     "SSOConfigUpdatedTrigger",
     "ConfigureSSOConnectorTask",
     "Register -> Upload metadata -> Map claims -> Test -> Enable"),

    (73, "Account: SSL and Certificates Write",
     "Certificate issuance, renewal, validation, deployment, and revocation.",
     "CertExpiryTrigger | CertRequestedTrigger",
     "IssueDeployCertificateTask",
     "Request -> Validate -> Issue -> Deploy -> Renew -> Revoke"),

    (74, "Cloud Email Security: Write",
     "Anti-spam, DLP, phishing, and attachment scanning for email security.",
     "EmailReceivedTrigger | SecurityAlertTrigger",
     "ConfigureEmailSecurityPolicyTask",
     "Scan -> Classify -> Filter -> Quarantine -> Notify"),

    (75, "Email Routing Account Rules Read",
     "Match conditions, actions, forwarding, and aliases for email routing rules.",
     "EmailRoutingConfigTrigger",
     "ReadEmailRoutingRuleTask",
     "List -> Validate -> Audit -> Report"),

    (76, "Email Routing Addresses Write",
     "Aliases, destinations, and forwarding addresses for email routing.",
     "EmailAddressCreatedTrigger",
     "ManageEmailRoutingAddressTask",
     "Create -> Verify DNS -> Activate -> Test"),

    (77, "Email Routing Suppressions Write",
     "Blocklists, opt-outs, and bounce handling for email suppressions.",
     "BounceReceivedTrigger | ComplaintTrigger",
     "ManageEmailSuppressionTask",
     "Add -> Validate -> Apply -> Monitor -> Remove"),

    (78, "Email Sending Write",
     "DKIM/SPF/DMARC, templates, batch, limits, and tracking for email sending.",
     "EmailSendTrigger | DeliveryEventTrigger",
     "SendEmailTask | ConfigureEmailSenderTask",
     "Compose -> Validate -> Queue -> Send -> Track -> Retry"),

    (79, "Calls Write",
     "WebRTC rooms, participants, recording, and quality for Calls.",
     "CallInitiatedTrigger | ParticipantJoinTrigger",
     "ManageCallSessionTask",
     "Create room -> Join -> Negotiate media -> Stream -> Record -> End"),

    (80, "Images Write",
     "Upload, resizing, format conversion, metadata, and variants for Images.",
     "ImageUploadedTrigger",
     "UploadTransformImageTask",
     "Upload -> Validate -> Transform -> Store -> Deliver"),

    (81, "MoQ Write",
     "Media over QUIC ingest, distribution, and latency settings.",
     "MoQStreamStartTrigger",
     "ConfigureMoQEndpointTask",
     "Ingest -> Transcode -> Distribute -> Playback -> Monitor"),

    (82, "Stream Write",
     "Live/VOD, transcoding, renditions, DRM, and manifests for Stream.",
     "StreamStartedTrigger | StreamEndedTrigger",
     "ManageStreamTask",
     "Create -> Ingest -> Transcode -> Publish -> View -> Archive"),

    (83, "Load Balancers Account Write",
     "Pools, origins, steering, failover, and health checks for load balancers.",
     "LoadBalancerConfigTrigger | PoolHealthChangeTrigger",
     "ConfigureLoadBalancerTask",
     "Create LB -> Define pools -> Attach health checks -> Deploy -> Test"),

    (84, "Address Maps Write",
     "IP/region-to-pool mapping, weighted routing, and geo-steering.",
     "AddressMapUpdatedTrigger",
     "ManageAddressMapTask",
     "Define mappings -> Assign priority -> Validate -> Deploy"),

    (85, "Account Waiting Rooms Read",
     "Queue stats, active users, wait time, and history for waiting rooms.",
     "WaitingRoomEventTrigger",
     "ReadWaitingRoomMetricsTask",
     "Poll -> Calculate -> Report -> Alert"),

    (86, "China Network Steering Write",
     "Routing, ICP, acceleration, and compliance for China network steering.",
     "SteeringConfigUpdatedTrigger",
     "ConfigureChinaSteeringTask",
     "Verify compliance -> Configure routing -> Activate -> Test"),

    (87, "Connectivity Directory Admin",
     "Peering, partners, service endpoints, and connectivity information.",
     "ConnectivityUpdatedTrigger",
     "ManageConnectivityDirectoryTask",
     "Register -> Verify -> Peer -> Activate -> Monitor"),

    (88, "IP Prefixes: Write",
     "Announced prefixes, origins, ASNs, RPKI, and authorization.",
     "PrefixAnnouncementTrigger",
     "ManageIPPrefixTask",
     "Register -> Authorize -> Announce -> Validate -> Monitor"),

    (89, "IP Prefixes: BGP On Demand Write",
     "Dynamic route advertisement, withdrawal, and scheduling.",
     "BGPTriggerEventTrigger",
     "ControlBGPAnnouncementTask",
     "Request -> Validate -> Announce -> Maintain -> Withdraw"),

    (90, "Magic Firewall Write",
     "Packet-level rules, L3/L4, stateful, and logging for Magic Firewall.",
     "MagicFirewallRuleChangeTrigger",
     "ConfigureMagicFirewallTask",
     "Define rule -> Set action -> Order -> Deploy -> Test"),

    (91, "Magic Network Monitoring Admin",
     "Flow sampling, path analysis, latency, and loss for network monitoring.",
     "NetworkAnomalyTrigger",
     "ManageNetworkMonitoringTask",
     "Enable sampling -> Collect -> Analyze -> Alert -> Report"),

    (92, "Magic Transit Write",
     "IPs, prefixes, DDoS protection, traffic steering, and peering for Magic Transit.",
     "MagicTransitConfigTrigger",
     "ProvisionMagicTransitTask",
     "Announce prefix -> Configure -> Activate -> Verify traffic"),

    (93, "Magic WAN Write",
     "Site-to-cloud, site-to-site, GRE/IPsec, and policies for Magic WAN.",
     "WANConnectionTrigger",
     "ConfigureMagicWANTask",
     "Create tunnels -> Establish -> Configure routing -> Activate"),

    (94, "Magic Firewall Packet Captures - Write PCAPs API",
     "Filter, duration, sampling, storage, and export of PCAP captures.",
     "PacketCaptureTrigger | SecurityEventTrigger",
     "CapturePacketsTask",
     "Define filter -> Start -> Capture -> Stop -> Export -> Analyze"),

    (95, "Logs Write",
     "Log retention, sampling, destinations, fields, and exports.",
     "LogConfigUpdatedTrigger",
     "ConfigureLogpushTask",
     "Select fields -> Set destination -> Enable -> Verify delivery"),

    (96, "Intel Write",
     "Threat feeds, IOCs, domain/IP reputation, and signatures.",
     "IntelFeedUpdatedTrigger",
     "UpdateThreatIntelTask",
     "Fetch -> Process -> Enrich -> Deploy -> Block/Alert"),

    (97, "Radar Read",
     "Internet traffic stats, outages, trends, and BGP changes from Radar.",
     "RadarDataUpdatedTrigger",
     "ReadRadarDataTask",
     "Query -> Analyze -> Visualize -> Report"),

    (98, "Account Analytics Read",
     "Usage, traffic, performance, errors, and reports for account analytics.",
     "AnalyticsReportTrigger | ScheduleTrigger",
     "QueryAnalyticsTask",
     "Select metrics -> Query -> Aggregate -> Generate -> Distribute"),

    (99, "Access: Apps and Policies Write",
     "Application definitions, access policies, and criteria.",
     "AccessPolicyUpdatedTrigger",
     "ManageAccessAppAndPolicyTask",
     "Define app -> Create policy -> Assign -> Test -> Activate"),

    (100, "Access: Apps Write",
     "App types, URLs, session duration, and auth methods for Access apps.",
     "AccessAppConfigTrigger",
     "RegisterAccessAppTask",
     "Register -> Configure -> Attach policy -> Publish"),

    (101, "Access: Audit Logs Read",
     "Audit events, filtering, export, and retention for Access audit logs.",
     "AuditLogGeneratedTrigger",
     "ReadAccessAuditLogTask",
     "Collect -> Filter -> Review -> Archive -> Report"),

    (102, "Access: Device Posture Write",
     "Checks, OS, disk encryption, firewall, and client version for device posture.",
     "DevicePostureUpdatedTrigger",
     "ConfigureDevicePostureCheckTask",
     "Define checks -> Collect -> Evaluate -> Allow/Block"),

    (103, "Access: Custom Pages Write",
     "Login, denied, error, and consent pages with branding.",
     "AccessPageRequestedTrigger",
     "UploadAccessCustomPageTask",
     "Design -> Upload -> Assign -> Activate"),

    (104, "Access: Identity Providers Write",
     "SAML/OIDC, SCIM, authentication methods, and attribute mapping for IdPs.",
     "IdPConfigUpdatedTrigger",
     "RegisterIdentityProviderTask",
     "Register -> Configure -> Map attributes -> Test -> Enable"),

    (105, "Access: Groups Write",
     "User grouping, dynamic criteria, and membership sync.",
     "GroupMembershipChangedTrigger",
     "ManageAccessGroupTask",
     "Create -> Add members -> Assign policies -> Sync"),

    (106, "Access: Keys Write",
     "Service auth keys, expiry, scope, and revocation.",
     "AccessKeyCreatedTrigger",
     "ManageAccessKeyTask",
     "Create -> Scope -> Distribute -> Rotate -> Revoke"),

    (107, "Access: Mutual TLS Certificates Write",
     "Client certs, CA bundles, validation rules, and revocation for mTLS.",
     "MTLSCertUploadedTrigger",
     "UploadMTLSCertificateTask",
     "Upload CA -> Require cert -> Validate -> Enforce"),

    (108, "Access: Organizations Write",
     "Org structure, domains, branding, settings, and invites.",
     "OrganizationCreatedTrigger",
     "ManageAccessOrganizationTask",
     "Create -> Configure domains -> Invite admins -> Setup IdP"),

    (109, "Access: Organizations, Identity Providers, and Groups Write",
     "Unified provisioning, relationships, and mappings across org, IdP, and groups.",
     "OrgStructureUpdatedTrigger",
     "SyncOrgIdPGroupTask",
     "Sync IdP -> Map groups -> Assign org -> Provision users"),

    (110, "Access: Policies Write",
     "Rules, precedence, actions, include/exclude, and conditions for policies.",
     "AccessPolicyTrigger",
     "CreateAccessPolicyTask",
     "Define -> Order -> Test -> Enable -> Audit"),

    (111, "Access: Policy Test Write",
     "Simulation, user/device context, and expected result for policy tests.",
     "PolicyTestRunTrigger",
     "TestAccessPolicyTask",
     "Select context -> Run simulation -> Compare -> Report -> Adjust"),

    (112, "Access: Population Write",
     "User directory, scope, sync, and filters for populations.",
     "PopulationUpdatedTrigger",
     "ManageAccessPopulationTask",
     "Sync source -> Filter -> Store -> Update policies"),

    (113, "Access: SAML Certificates Write",
     "Signing/encryption certs, metadata, and rollover for SAML.",
     "SAMLCertExpiryTrigger",
     "ManageSAMLCertificateTask",
     "Generate -> Upload -> Update IdP -> Rollover -> Revoke old"),

    (114, "Access: Service Tokens Write",
     "Non-human authentication, scoped, expiry, and rotation for service tokens.",
     "ServiceTokenCreatedTrigger",
     "IssueServiceTokenTask",
     "Create -> Scope -> Issue -> Rotate -> Revoke"),

    (115, "Access: SCIM Logs Read",
     "Sync events, errors, user changes, and timestamps for SCIM logs.",
     "SCIMSyncCompletedTrigger",
     "ReadSCIMLogTask",
     "Collect -> Review -> Troubleshoot -> Report"),

    (116, "Access: SSH Auditing Write",
     "Session logs, commands, file transfers, and keylogging for SSH auditing.",
     "SSHSessionStartTrigger",
     "ConfigureSSHAuditingTask",
     "Enable -> Capture -> Store -> Review -> Archive"),

    (117, "Access: Tags Write",
     "Resource tagging, policy-based, and RBAC grouping for Access tags.",
     "AccessTagUpdatedTrigger",
     "ApplyAccessTagTask",
     "Define -> Assign -> Enforce -> Report"),

    (118, "Access: Users Write",
     "User records, profile, status, MFA, and devices.",
     "UserCreatedTrigger | UserLoginTrigger",
     "ManageAccessUserTask",
     "Create -> Invite -> Enroll MFA -> Provision -> Deprovision"),

    (119, "Tunnel Write",
     "cloudflared ingress, configuration, warp-routing, and HA for tunnels.",
     "TunnelConfigTrigger | TunnelConnectedTrigger",
     "ManageTunnelTask",
     "Create -> Install connector -> Configure ingress -> Run -> Verify"),

    (120, "CASB Write",
     "SaaS app connectors, data policies, DLP, and access controls for CASB.",
     "CASBConfigUpdatedTrigger",
     "ConfigureCASBIntegrationTask",
     "Connect SaaS -> Scan -> Apply policies -> Monitor -> Remediate"),

    (121, "CDS Compute Account Write",
     "Distributed compute, edge functions, and scheduling for CDS.",
     "CDSJobTrigger",
     "DeployCDSComputeTask",
     "Package -> Deploy -> Schedule -> Execute -> Collect results"),

    (122, "One Connector: cloudflared Write",
     "Installation, configuration, tunnels, metrics, and updates for cloudflared.",
     "CloudflaredConfigUpdatedTrigger",
     "ConfigureCloudflaredTask",
     "Install -> Authenticate -> Create tunnel -> Run -> Monitor"),

    (123, "One Connector: WARP Write",
     "Client configuration, encryption, split tunnel, and firewall for WARP.",
     "WARPConfigUpdatedTrigger",
     "ConfigureWARPConnectorTask",
     "Install -> Configure -> Enable -> Connect -> Verify"),

    (124, "One Connectors Write",
     "Unified connector management, fleet, and versions.",
     "ConnectorRegisteredTrigger",
     "ManageOneConnectorTask",
     "Register -> Configure -> Deploy -> Update -> Monitor"),

    (125, "One Networks Write",
     "Private networks, routes, CIDR, and VPC peering.",
     "NetworkConfigUpdatedTrigger",
     "ManageOneNetworkTask",
     "Define CIDR -> Create routes -> Connect -> Verify reachability"),

    (126, "DLS: Write",
     "Data loss prevention patterns, detection rules, and redaction.",
     "DLPRuleUpdatedTrigger | SensitiveDataDetectedTrigger",
     "ConfigureDLSPolicyTask",
     "Define patterns -> Scan -> Detect -> Redact/Block -> Log/Alert"),

    (127, "DEX Write",
     "Digital experience monitoring, synthetic tests, and real-user monitoring.",
     "DEXTestTrigger",
     "ConfigureDEXTestTask",
     "Define tests -> Deploy -> Collect -> Analyze -> Alert -> Report"),

    (128, "Zero Trust Write",
     "Assume-breach, least-privilege, identity-centric, and micro-perimeter principles.",
     "ZeroTrustConfigTrigger",
     "ConfigureZeroTrustTask",
     "Identify assets -> Classify -> Design policies -> Deploy -> Validate -> Iterate"),

    (129, "Zero Trust Resilience Write",
     "HA, failover, disaster recovery, and redundancy for Zero Trust.",
     "ResilienceEventTrigger | FailoverTrigger",
     "ConfigureZeroTrustResilienceTask",
     "Design redundancy -> Test failover -> Monitor -> Recover -> Validate"),

    (130, "Zero Trust: Seats Write",
     "License assignment, user count, billing, and enable/disable for seats.",
     "SeatAssignmentTrigger",
     "ManageZeroTrustSeatTask",
     "Assign -> Enable -> Sync -> Reclaim -> Report"),

    (131, "Zero Trust: PII Read",
     "PII access, minimization, consent, export, and deletion.",
     "PIIAccessRequestTrigger",
     "ReadZeroTrustPIITask",
     "Request -> Auth -> Minimize -> Access -> Export/Delete -> Audit"),
]
