# -*- coding: utf-8 -*-
"""Spec data part A: capabilities 1-65 (of 131).

Each entry: (num, title, protocol_purpose, triggers, tasks, workflow_steps)
triggers/tasks may contain " | " separators; workflow uses " -> ".
Transcribed from the user's Cloudflare Permissions & Capabilities specification.
"""

ENTRIES_A = [
    (1, "Agent Memory Write",
     "Defines memory CRUD, persistence, scope, TTL, and access controls for agent memory records.",
     "AgentMemoryUpdatedTrigger (on memory entry created/updated/expired)",
     "WriteAgentMemoryTask (persist/modify agent memory records)",
     "Validate -> Write -> Replicate -> Notify"),

    (2, "CF Agents Write",
     "Agent lifecycle, configuration, deployment, and permissions management.",
     "AgentDeploymentTrigger | AgentConfigChangeTrigger",
     "ProvisionUpdateAgentTask",
     "Validate spec -> Deploy -> Health check -> Activate"),

    (3, "AI Gateway Write",
     "Routing, rate limits, model access, authentication, and logging for AI inference.",
     "AIRequestReceivedTrigger | AIMetricThresholdTrigger",
     "ConfigureAIGatewayTask",
     "Define routes -> Attach models -> Set policies -> Deploy"),

    (4, "AI Search Write",
     "Index management, ingestion, embeddings, and ranking configuration for AI search.",
     "DocumentIngestedTrigger | IndexUpdatedTrigger",
     "ManageAISearchIndexTask",
     "Extract -> Embed -> Index -> Optimize"),

    (5, "Auto Rag Write",
     "Source connectors, chunking, retrieval logic, and generation settings for RAG pipelines.",
     "NewDataSourceDetectedTrigger | ScheduleRAGUpdateTrigger",
     "ConfigureAutoRAGTask",
     "Connect source -> Chunk -> Embed -> Store -> Test query"),

    (6, "Websearch Write",
     "Search scope, allowed domains, rate limits, and result filtering for web search.",
     "SearchConfigUpdatedTrigger",
     "UpdateWebsearchConfigTask",
     "Validate -> Apply -> Test -> Audit"),

    (7, "Workers AI Write",
     "Model bindings, inference endpoints, and usage quotas for Workers AI.",
     "AIInferenceRequestTrigger | ModelDeploymentTrigger",
     "DeployWorkersAIModelTask",
     "Select model -> Bind worker -> Set limits -> Deploy endpoint"),

    (8, "Workers Scripts Write",
     "Script upload, validation, bundling, and versioning for Workers.",
     "ScriptUploadedTrigger | GitPushTrigger",
     "UploadUpdateWorkerScriptTask",
     "Validate -> Build -> Upload -> Activate -> Test"),

    (9, "Workers Containers Write",
     "OCI artifacts, registry auth, resource allocation, and scaling for container workloads.",
     "ContainerImagePushedTrigger | ScaleEventTrigger",
     "DeployWorkerContainerTask",
     "Pull image -> Validate -> Deploy -> Start -> Health check"),

    (10, "Workers CI Write",
     "Build pipelines, test runners, and deploy gates for continuous integration.",
     "CommitPushedTrigger | PullRequestTrigger | ScheduleTrigger",
     "RunWorkersCITask",
     "Lint -> Test -> Build -> Scan -> Deploy"),

    (11, "Hyperdrive Write",
     "Origin configuration, connection pooling, caching rules, and timeouts for Hyperdrive.",
     "HyperdriveConfigUpdatedTrigger",
     "ConfigureHyperdriveTask",
     "Register origin -> Set pool -> Apply caching -> Test connectivity"),

    (12, "Pipelines Write",
     "Data pipeline definitions, transforms, sinks, and sources.",
     "PipelineEventTrigger | SchedulePipelineTrigger",
     "ManagePipelineTask",
     "Define schema -> Build stages -> Connect sources/sinks -> Activate"),

    (13, "Chamber Write -> Secrets Store",
     "Secret storage, rotation, access grants, and encryption for Chamber secrets.",
     "SecretRotatedTrigger | SecretAccessedTrigger",
     "ManageSecretTask",
     "Create -> Encrypt -> Store -> Grant access -> Rotate"),

    (14, "Secrets Store Write",
     "Cross-service secret injection and versioning on top of the secrets store.",
     "SecretUpdatedTrigger | SecretExpiryTrigger",
     "WriteSecretToStoreTask",
     "Validate -> Encrypt -> Store -> Inject -> Audit"),

    (15, "D1 Write",
     "SQL schema, migrations, query patterns, and access controls for D1.",
     "MigrationTrigger | WriteQueryTrigger",
     "ExecuteD1QueryTask | RunD1MigrationTask",
     "Validate SQL -> Backup -> Apply migration -> Verify"),

    (16, "Workers KV Storage Write",
     "Key scope, TTL, atomic ops, bulk upload, and replication for Workers KV.",
     "KVKeyWrittenTrigger | KVExpiryTrigger",
     "WriteKVEntryTask | BulkWriteKVTask",
     "Validate keys -> Batch -> Write -> Replicate -> Verify"),

    (17, "Workers R2 Storage Write",
     "Bucket, object, ACL, lifecycle, and multipart upload management for R2.",
     "ObjectUploadedTrigger | BucketConfigTrigger",
     "UploadR2ObjectTask | ManageR2BucketTask",
     "Validate -> Upload -> Index -> Set lifecycle -> Purge cache"),

    (18, "Workers R2 SQL Read",
     "Query syntax, catalog mapping, permissions, and pagination for R2 SQL.",
     "R2SQLQueryTrigger",
     "ExecuteR2SQLQueryTask",
     "Auth -> Parse -> Plan -> Execute -> Return results"),

    (19, "Workers R2 Data Catalog Write",
     "Dataset metadata, schema registry, and partition information for the R2 catalog.",
     "CatalogEntryUpdatedTrigger",
     "UpdateR2DataCatalogTask",
     "Register schema -> Index -> Tag -> Publish"),

    (20, "Vectorize Write",
     "Vector ingestion, dimensions, indexing, and distance metrics for Vectorize.",
     "VectorBatchTrigger | EmbeddingGeneratedTrigger",
     "IngestVectorsTask | BuildVectorIndexTask",
     "Generate embeddings -> Insert -> Index -> Optimize"),

    (21, "Messaging Read",
     "Topic consumption, offset management, filtering, and acknowledgement for messaging.",
     "MessageAvailableTrigger | MessageReceivedTrigger",
     "ReadMessageTask | PollMessagesTask",
     "Pull -> Validate -> Process -> Ack -> Commit offset"),

    (22, "Pubsub Configuration Write",
     "Topics, subscriptions, dead-letter, retries, and auth for Pub/Sub.",
     "PubsubConfigChangeTrigger",
     "ConfigurePubsubTask",
     "Create topic -> Create sub -> Set DLQ -> Attach policy -> Deploy"),

    (23, "Queues Write",
     "Queue creation, batching, concurrency, dead-letter, and delays for Queues.",
     "QueueMessageEnqueueTrigger | QueueDepthThresholdTrigger",
     "EnqueueMessageTask | ManageQueueTask",
     "Send -> Batch -> Deliver -> Process -> Ack/Retry"),

    (24, "Workers Observability Write",
     "Metrics, alerts, dashboards, and sampling rates for Workers observability.",
     "MetricThresholdTrigger | ObservabilityConfigTrigger",
     "ConfigureObservabilityTask",
     "Define metrics -> Set retention -> Build dash -> Create alerts -> Deploy"),

    (25, "Workers Observability Telemetry Write",
     "OpenTelemetry traces, spans, logs, and exporters for telemetry.",
     "TelemetryIngestTrigger",
     "ExportTelemetryTask | ConfigureTelemetryTask",
     "Instrument -> Collect -> Sample -> Export -> Store"),

    (26, "Realtime Admin",
     "Presence, rooms, connections, events, and auth for realtime sessions.",
     "ClientConnectedTrigger | RoomEventTrigger",
     "ManageRealtimeSessionTask",
     "Auth -> Join room -> Broadcast -> Monitor -> Disconnect"),

    (27, "Constellation Write",
     "Distributed graph nodes, edges, discovery, and state sync for Constellation.",
     "NodeJoinTrigger | GraphUpdateTrigger",
     "UpdateConstellationGraphTask",
     "Register node -> Sync state -> Reconcile -> Broadcast"),

    (28, "Flagship Write",
     "Feature flags, rollouts, targeting, and experiments.",
     "FlagChangedTrigger | ScheduleFlagTrigger",
     "ManageFeatureFlagTask",
     "Define -> Target -> Rollout -> Monitor -> Adjust"),

    (29, "MCP Portals Write",
     "Portal configuration, access, integrations, and UI components for MCP portals.",
     "PortalConfigUpdatedTrigger",
     "ConfigureMCPPortalTask",
     "Build -> Configure auth -> Integrate -> Publish"),

    (30, "Account DNS Settings Write",
     "Nameservers, TTL, DNSSEC, records, and policies for DNS settings.",
     "DNSConfigChangeTrigger",
     "UpdateDNSSettingTask",
     "Validate -> Apply -> Propagate -> Verify"),

    (31, "DNS Firewall Write",
     "Allowlists/blocklists, response filtering, and rate limits for DNS firewall.",
     "DNSQueryTrigger | DNSFirewallRuleChangeTrigger",
     "ManageDNSFirewallRuleTask",
     "Define rule -> Attach -> Test -> Activate"),

    (32, "DNS View Write",
     "Split DNS, views, and geography-based resolution.",
     "DNSViewConfigTrigger",
     "ConfigureDNSViewTask",
     "Define view -> Assign zones -> Set match -> Deploy"),

    (33, "Registrar Domains Admin",
     "Domain registration, transfer, renewal, auth codes, and lock.",
     "DomainEventTrigger | ExpiryWarningTrigger",
     "ManageDomainTask",
     "Check availability -> Register -> Configure DNS -> Activate"),

    (34, "Registrar Sandbox Domains Admin",
     "Test domain provisioning, isolation, expiry, and cleanup.",
     "SandboxDomainCreatedTrigger",
     "ProvisionSandboxDomainTask",
     "Create -> Assign -> Test -> Expire -> Cleanup"),

    (35, "Account Abuse Protection PII Read",
     "PII access scope, redaction, audit, and legal holds for abuse protection.",
     "PIIAccessRequestTrigger | AbuseReportTrigger",
     "ReadAbusePIIRecordTask",
     "Request -> Auth -> Redact -> Review -> Action -> Log"),

    (36, "Account Firewall Access Rules Write",
     "IP, ASN, country, URI, and user-agent matching with actions for access rules.",
     "FirewallRuleChangeTrigger | AttackDetectedTrigger",
     "CreateFirewallRuleTask",
     "Define -> Validate -> Order -> Apply -> Test"),

    (37, "Account Security Center Insights Write",
     "Findings, risks, recommendations, and reports for Security Center.",
     "SecurityScanCompleteTrigger | InsightGeneratedTrigger",
     "UpdateSecurityInsightTask",
     "Scan -> Analyze -> Generate insight -> Prioritize -> Notify"),

    (38, "Account WAF Write",
     "Managed rules, custom rules, paranoia level, sensitivity, and actions for WAF.",
     "WAFRuleUpdatedTrigger | AttackDetectedTrigger",
     "ConfigureWAFTask",
     "Select ruleset -> Tune -> Test -> Enable -> Monitor"),

    (39, "Allow Request Tracer Read",
     "Sampling, tracing, hop-by-hop, and logging for request tracing.",
     "TraceRequestTrigger | SamplingTrigger",
     "TraceRequestTask",
     "Capture -> Follow path -> Collect -> Analyze -> Report"),

    (40, "Application Security Reports Read",
     "Vulnerabilities, attack stats, and endpoint risk reporting.",
     "ReportGeneratedTrigger | ScheduleReportTrigger",
     "GenerateAppSecReportTask",
     "Collect data -> Analyze -> Generate -> Distribute -> Archive"),

    (41, "One Write",
     "Unified platform configuration and single-pane settings for Cloudflare One.",
     "OneConfigChangeTrigger",
     "UpdateCloudflareOneConfigTask",
     "Update -> Sync across services -> Validate -> Notify"),

    (42, "DDoS Botnet Feed Write",
     "IOCs, IP reputation, signatures, and update frequency for botnet feeds.",
     "FeedUpdatedTrigger | ScheduleFeedSyncTrigger",
     "IngestBotnetFeedTask",
     "Fetch -> Validate -> Merge -> Deploy to edge -> Activate"),

    (43, "DDoS Protection Write",
     "Detection thresholds, mitigation actions, and auto-mitigation for DDoS protection.",
     "DDoSEventDetectedTrigger",
     "ConfigureDDoSProtectionTask",
     "Detect -> Classify -> Activate mitigation -> Monitor -> Release"),

    (44, "Field Extractors Write",
     "Regex, JSON, XPath, request/response fields, and transforms for field extraction.",
     "ExtractorConfigTrigger",
     "CreateFieldExtractorTask",
     "Define pattern -> Test -> Attach to rule -> Deploy"),

    (45, "Fraud Events Write",
     "Event schema, risk scoring, detection rules, and thresholds for fraud events.",
     "FraudEventDetectedTrigger",
     "LogFraudEventTask | ScoreFraudRiskTask",
     "Collect -> Score -> Flag -> Action -> Report"),

    (46, "Fraud Feedback Write",
     "Labels, corrections, and model retraining loop for fraud feedback.",
     "FraudFeedbackSubmittedTrigger",
     "SubmitFraudFeedbackTask",
     "Accept -> Validate -> Store -> Retrain model -> Update rules"),

    (47, "HTTP Applications Write",
     "Origin, routing, protocol, headers, timeouts, and keepalive for HTTP applications.",
     "HTTPAppConfigTrigger",
     "ManageHTTPApplicationTask",
     "Define origin -> Set routing -> Configure headers -> Deploy -> Test"),

    (48, "IOT Write",
     "Device registry, auth, message routing, and device shadows for IoT.",
     "DeviceConnectedTrigger | DeviceMessageTrigger",
     "ManageIoTDeviceTask",
     "Register -> Auth -> Provision -> Monitor -> Update"),

    (49, "L4 DDoS Managed Ruleset Write",
     "Packet filtering, flood protection, and anomaly detection for L4 DDoS rulesets.",
     "L4DDoSRulesetUpdatedTrigger",
     "DeployL4DDoSRulesetTask",
     "Select -> Tune -> Deploy -> Monitor -> Adjust"),

    (50, "Page Shield Read",
     "Script monitoring, CSP, and code injection detection for Page Shield.",
     "ScriptIncludedTrigger | PageShieldAlertTrigger",
     "ScanPageShieldTask",
     "Monitor scripts -> Detect anomalies -> Alert -> Log"),

    (51, "Tag Write",
     "Resource tagging, taxonomy, and policy-based assignment.",
     "TagAddedTrigger | TagUpdatedTrigger",
     "ApplyResourceTagTask",
     "Define taxonomy -> Assign -> Propagate -> Enforce policies"),

    (52, "Trust and Safety Write",
     "Content policies, moderation rules, reporting, and takedown.",
     "ContentReportedTrigger | PolicyUpdatedTrigger",
     "UpdateTrustSafetyPolicyTask",
     "Review -> Classify -> Action -> Notify -> Log"),

    (53, "Turnstile Sites Write",
     "Site keys, challenge settings, widget configuration, and allowed origins for Turnstile.",
     "TurnstileConfigUpdatedTrigger",
     "ConfigureTurnstileSiteTask",
     "Register site -> Set challenge mode -> Install -> Verify"),

    (54, "URL Scanner Write",
     "Scan targets, frequency, checks, and risk categories for URL scanning.",
     "URLSubmittedTrigger | ScheduleScanTrigger",
     "ScanURLTask",
     "Submit -> Scan -> Analyze -> Score -> Flag/Report"),

    (55, "Account Custom Error Rules Write",
     "Status codes, response bodies, redirects, and caching for custom error rules.",
     "ErrorResponseTrigger | RuleConfigTrigger",
     "CreateCustomErrorRuleTask",
     "Define -> Test -> Order -> Activate"),

    (56, "Account Custom Pages Write",
     "Error, challenge, and maintenance pages with hosting for custom pages.",
     "CustomPageRequestedTrigger | PageUpdatedTrigger",
     "UploadCustomPageTask",
     "Design -> Upload -> Assign -> Activate -> Verify"),

    (57, "Account Rule Lists Write",
     "IPs, patterns, strings, bulk import/export, and versioning for rule lists.",
     "RuleListUpdatedTrigger",
     "ManageRuleListTask",
     "Create -> Import items -> Attach -> Deploy -> Monitor"),

    (58, "Account Rulesets Write",
     "Rule composition, execution order, phase, and expression language for rulesets.",
     "RulesetDeployedTrigger",
     "DeployRulesetTask",
     "Compose -> Validate -> Test -> Deploy -> Activate"),

    (59, "Transform Rules Write",
     "Header modification, URI rewrite, host, path, and query string transforms.",
     "TransformRuleUpdatedTrigger",
     "CreateTransformRuleTask",
     "Define match -> Set action -> Order -> Test -> Apply"),

    (60, "Mass URL Redirects Write",
     "Bulk mappings, status codes, preserve-query, and priority for mass redirects.",
     "RedirectConfigUpdatedTrigger | BulkImportTrigger",
     "ImportRedirectsTask",
     "Import CSV -> Validate -> Deploy -> Test -> Verify"),

    (61, "Select Configuration Write",
     "Conditional selection, feature targeting, and environment routing.",
     "SelectConfigUpdatedTrigger",
     "UpdateSelectConfigurationTask",
     "Define criteria -> Assign targets -> Validate -> Deploy"),

    (62, "Artifacts Write",
     "Binary assets, versions, signing, distribution, and retention for artifacts.",
     "ArtifactUploadedTrigger",
     "UploadArtifactTask",
     "Build -> Sign -> Upload -> Index -> Distribute"),

    (63, "Account API Gateway",
     "API definitions, auth, quotas, transforms, and CORS for the API gateway.",
     "APIRequestTrigger | GatewayConfigTrigger",
     "ConfigureAPIGatewayTask",
     "Define API -> Set auth -> Attach policies -> Deploy -> Test"),

    (64, "Account API Tokens Write",
     "Token creation, scopes, expiry, rotation, and revocation.",
     "TokenCreatedTrigger | TokenExpiryTrigger",
     "IssueAPITokenTask | RevokeAPITokenTask",
     "Request -> Scope -> Create -> Issue -> Rotate -> Revoke"),

    (65, "Account Custom Asset Write",
     "Uploaded assets, hashes, cache control, and distribution for custom assets.",
     "AssetUploadedTrigger",
     "UploadCustomAssetTask",
     "Upload -> Validate -> Hash -> Distribute -> Purge cache"),
]
